<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows7.0</TargetFramework>
    <RootNamespace>xCoreSDK_CSharp</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Platforms>x64</Platforms>
    <Configurations>Release</Configurations>
    <ForceDesignerDpiUnaware>true</ForceDesignerDpiUnaware>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="xCoreSDK_cli">
      <HintPath>xcore.lib\xCoreSDK_cli.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>